version: '3.8'

services:
  backend:
    image: sororiri/race:0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5500:5500
    environment:
      - TYPEORM_PASSWORD=test

